name: check
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  checklinks:
    name: Linux
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.1
      - name: Setup Rubygems, Bundler, jekyll
        run: | 
          gem update --system --no-document
          gem update bundler --no-document
          gem install jekyll bundler
          bundle install
      - name: Build jekyll website with drafts
        run: bundle exec jekyll build --drafts
      - name: Check for broken links
        run: |
          bundle exec htmlproofer  ./_site --disable-external --no-enforce-https --allow-missing-href --no-check-internal-hash
      - name: check more
        run: |
          _scripts/run_check.pl
